projects:
  snowapp-dev:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - src/API.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: us-east-2
        apiId: 6oqixsx4dnhhbjs44o256d5y6y
        maxDepth: 6
extensions:
  amplify:
    version: 3
